include:
  - path: ./auth-service/docker-compose.yml
  - path: ./user-service/docker-compose.yml

services:
  rabbitmq:
    image: rabbitmq:4.1.0-rc.2-management
    container_name: rabbitmq
    restart: always
    env_file:
      - ./.env
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672" # RabbitMQ Management UI
      - "${RABBITMQ_PORT}:5672"   # RabbitMQ AMQP protocol
    expose:
      - "15672" # RabbitMQ Management UI
      - "5672"  # RabbitMQ AMQP protocol
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservice-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
# ボリュームの定義
volumes:
  rabbitmq_data:
# 共通ネットワークの定義
networks:
  microservice-network:
    name: microservice-network
    driver: bridge